### ISSUE TITLE
@RelayedQuery() doesn't work on Nestjs 7 version. 

### ISSUE THREAD

**Issue by ZhoraGrig** [wemaintain/auto-relay#31] opened 2020-05-07 11:39 UTC
I don't get any errors or anything, but my @RelayedQuery decorated function don't show up and doesn't generate types and query.

**Comment by kodeine** [comment] 2020-05-08 15:53
how are you using it? code > words :)

**Comment by kodeine** [comment] 2020-05-09 05:54
agreed. it doesnt work on nest 7

**Comment by ZhoraGrig** [comment] 2020-05-09 12:03
Hi @Superd22 can you fix it ?

**Comment by Superd22** [comment] 2020-05-09 12:46
Hey @ZhoraGrig @kodeine , this is a dupe of #23 ;)

**Closed by Superd22** 2020-05-09 12:46 UTC
